version: '3.8'

services:
  redis:
    image: redis:7.0.9-alpine
    command: redis-server --bind 0.0.0.0
    ports:
      - 6379:6379

  app:
    build: .
    env_file:
      - .env
    ports:
      - 8501:8501  # Streamlit port
      - 8000:8000  # FastAPI port
    depends_on:
      - redis
    environment:
      - REDISHOST=redis